build:
  image: stormenroute/storm-enroute-build:0.6
  environment:
    - DEFINED=$$
    - SSH_KEY_PASS=$$SSH_KEY_PASS
    - SONATYPE_USER=$$SONATYPE_USER
    - SONATYPE_PASS=$$SONATYPE_PASS
  commands:
    - export DEFINED=$DEFINED"$SSH_KEY_PASS"
    - echo $DEFINED
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - |
      if [ "$SSH_KEY_PASS" != "$DEFINED" ]; then
        eval `ssh-agent -s`
        echo "Setting up ssh-agent."
        echo "exec cat" > ap-cat.sh
        chmod a+x ap-cat.sh
        export DISPLAY=1
        echo $SSH_KEY_PASS | SSH_ASKPASS=./ap-cat.sh ssh-add ~/.ssh/id_rsa
        rm ap-cat.sh
        export SSH_KEY_PASS=""
        export DISPLAY=""
      else
        export SONATYPE_USER=""
        export SONATYPE_PASS=""
      fi
    - echo "pull request no. $DRONE_PULL_REQUEST"
    - if [ "$DRONE_PULL_REQUEST" != "" ]; then (sbt test); else (sbt mecha-nightly); fi
